#!/usr/bin/env python3
"""Build the library index in README.md from library.json and the skill folders.

Usage:
    python3 scripts/build_index.py          # rewrite README.md
    python3 scripts/build_index.py --check  # exit 1 if README.md is out of date

library.json is the only place a human edits grouping, status and summary.
The skill name comes from each SKILL.md heading, so it cannot drift.
A skill folder that library.json does not list yet is shown under
"Not yet categorised" instead of being dropped.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
START = "<!-- library:start (generated by scripts/build_index.py; edit library.json) -->"
END = "<!-- library:end -->"
RUN_URL = "https://omo.space/run?slug={slug}"


def skill_title(slug: str) -> str:
    text = (ROOT / "skills" / slug / "SKILL.md").read_text(encoding="utf-8")
    m = re.search(r"^# (.+)$", text, re.M)
    return m.group(1).strip() if m else slug.replace("-", " ").title()


def skill_description(slug: str) -> str:
    text = (ROOT / "skills" / slug / "SKILL.md").read_text(encoding="utf-8")
    m = re.search(r"^description:\s*(.+)$", text, re.M)
    return m.group(1).strip().strip("\"'") if m else ""


def row(slug: str, meta: dict) -> str:
    title = skill_title(slug)
    summary = (meta.get("summary") or skill_description(slug)).replace("|", "\\|")
    if meta.get("status") == "hosted":
        run = f"[Run on Omo]({RUN_URL.format(slug=slug)})"
    else:
        run = "Spec only"
    return f"| [{title}](skills/{slug}/) | {summary} | {run} |"


def build_block(lib: dict, slugs: list[str]) -> str:
    skills = lib["skills"]
    hosted = sum(1 for s in slugs if skills.get(s, {}).get("status") == "hosted")
    out = [START, ""]
    out.append(
        f"**{len(slugs)} skills.** {hosted} run on omo.space today; "
        f"the other {len(slugs) - hosted} are open specs you can implement yourself."
    )
    out.append("")
    cats = lib["categories"]
    counts = {c["id"]: [s for s in slugs if skills.get(s, {}).get("category") == c["id"]] for c in cats}
    out.append("**Jump to:** " + " · ".join(
        f"[{c['title']}](#{anchor(c['title'])}) ({len(counts[c['id']])})" for c in cats if counts[c["id"]]
    ))
    out.append("")
    for c in cats:
        members = counts[c["id"]]
        if not members:
            continue
        # Runnable skills first, then alphabetical by title.
        members.sort(key=lambda s: (skills[s].get("status") != "hosted", skill_title(s).lower()))
        out += [f"### {c['title']}", "", c["blurb"], "", "| Skill | What it does | Run |", "| --- | --- | --- |"]
        out += [row(s, skills[s]) for s in members]
        out.append("")
    loose = sorted(s for s in slugs if s not in skills or skills[s].get("category") not in counts)
    if loose:
        out += ["### Not yet categorised", "", "Newly published. Add these to `library.json`.", "",
                "| Skill | What it does | Run |", "| --- | --- | --- |"]
        out += [row(s, skills.get(s, {})) for s in loose]
        out.append("")
    out.append(END)
    return "\n".join(out)


def anchor(title: str) -> str:
    a = title.lower()
    a = re.sub(r"[^a-z0-9 -]", "", a)
    return a.replace(" ", "-")


def main() -> int:
    lib = json.loads((ROOT / "library.json").read_text(encoding="utf-8"))
    slugs = sorted(p.name for p in (ROOT / "skills").iterdir() if (p / "SKILL.md").is_file())
    readme_path = ROOT / "README.md"
    readme = readme_path.read_text(encoding="utf-8")
    if START not in readme or END not in readme:
        print("README.md has no library markers", file=sys.stderr)
        return 2
    head, rest = readme.split(START, 1)
    _, tail = rest.split(END, 1)
    new = head + build_block(lib, slugs) + tail
    if "--check" in sys.argv:
        if new != readme:
            print("README.md is out of date: run python3 scripts/build_index.py", file=sys.stderr)
            return 1
        print("README.md index is current")
        return 0
    readme_path.write_text(new, encoding="utf-8")
    print(f"README.md index rebuilt: {len(slugs)} skills")
    return 0


if __name__ == "__main__":
    sys.exit(main())
